#@package _global_.results
#
base_dir: '../oceanbench-data-registry/results/osse_gf_nadir_sst'
outputs:
  methods:
    musti: {inp: '${....base_dir}/musti_nadir.nc', fns: ['${.....prepro.gssh.cfg}', '${.....postpro.default}']}
    4dvarnet: {inp: '${....base_dir}/4dvarnet.nc', fns: ['${.....prepro.out.cfg}', '${results.postpro.select}']}

defaults:
    - /processing/osse_gf_results@_global_.results
    - /task/osse_gf_nadir/task@_global_.task
    - /funcs@_global_.F
    - /processing/pipe@outputs.methods.musti
    - /processing/pipe@outputs.methods.4dvarnet
    - _self_
