#@package _global_.results
#
base_dir: '../oceanbench-data-registry/results/osse_gf_nadir'



outputs:
  eval:
    methods:
      bfn: {inp: '${results.base_dir}/bfn.nc', fns: ['${results.prepro.gssh.cfg}', '${results.postpro.default}']}
      miost: {inp: '${results.base_dir}/miost.nc', fns: ['${results.prepro.gssh.cfg}', '${results.postpro.default}']}
      dymost: {inp: '${results.base_dir}/dymost.nc', fns: ['${results.prepro.gssh.cfg}', '${results.postpro.default}']}
      4dvarnet: {inp: '${results.base_dir}/4dvarnet.nc', fns: ['${results.prepro.default.cfg}', '${results.postpro.default}']}
      nerf_mlp: {inp: '${results.base_dir}/nerf_mlp.nc', fns: ['${results.prepro.default.cfg}', '${results.postpro.default}']}
      nerf_siren: {inp: '${results.base_dir}/nerf_siren.nc', fns: ['${results.prepro.default.cfg}', '${results.postpro.default}']}
      nerf_ffn: {inp: '${results.base_dir}/nerf_ffn.nc', fns: ['${results.prepro.default.cfg}', '${results.postpro.default}']}
      duacs: {inp: '${results.base_dir}/duacs.nc', fns: ['${results.prepro.ssh_mod.cfg}', '${results.postpro.default}']}

  plots:
    maps:
      ref: ${results.outputs.eval.ref}
      methods:
        bfn: ${results.outputs.eval.methods.bfn}
        miost: ${results.outputs.eval.methods.miost}
        dymost: ${results.outputs.eval.methods.dymost}
        duacs: {inp: '${results.outputs.eval.methods.duacs}', fns: ['${F.call}', '${results.filter.cfg}', '${results.duacsselect.cfg}']}
        nerf_ffn: ${results.outputs.eval.methods.nerf_ffn}
        nerf_siren: ${results.outputs.eval.methods.nerf_siren}
        nerf_mlp: ${results.outputs.eval.methods.nerf_mlp}
        4dvarnet: ${results.outputs.eval.methods.4dvarnet}

filter:
  shape: GAUSSIAN
  scale: 7.
  n_steps: 0

duacsselect:
  lat: [33.5, 42.5] 
  lon: [-64.5, -55.5] 
  drop: False


defaults:
  - /processing/components/select_where@duacsselect
  - /processing/components/filter@filter
  - /processing/osse_gf_results@_global_.results
  - /task/osse_gf_nadir/task@_global_.task
  - /funcs@_global_.F
  - /processing/pipe@outputs.eval.methods.bfn
  - /processing/pipe@outputs.eval.methods.4dvarnet
  - /processing/pipe@outputs.eval.methods.duacs
  - /processing/pipe@outputs.eval.methods.dymost
  - /processing/pipe@outputs.eval.methods.miost
  - /processing/pipe@outputs.eval.methods.nerf_ffn
  - /processing/pipe@outputs.eval.methods.nerf_mlp
  - /processing/pipe@outputs.eval.methods.nerf_siren
  - /processing/pipe@outputs.plots.maps.methods.duacs
  - _self_
