

rescale_time:
  t0: "2012-10-22T12:00:00"

cfg:
  fns:
    - '${lib.to_dataset}'
    - '${lib.fill_nans}'
    - '${lib.rescale_space}'
    - '${...rescale_time.cfg}'
    - {_target_: "operator.itemgetter", _args_: [ssh]}
        
defaults:
  - /processing/lib@_global_.lib
  - /processing/pipe@cfg
  - /processing/components/rescale_time@rescale_time
  - /funcs@F
