
freq: 1D
cls: DataArray

cfg:
    fns:
    - _target_: 'xarray.${....cls}.resample'
      _partial_: True
      indexer: {time: '${.....freq}'}
    - _target_: 'xarray.core.resample.${....cls}Resample.mean'
      _partial_: True

defaults:
  - /processing/pipe@cfg
