
time: [null, null]
lat: [null, null]
lon: [null, null]
sel_type: sel
cls: DataArray

cfg:
    _target_: 'xarray.${..cls}.${..sel_type}'
    _partial_: true
    time: {_target_: builtins.slice, _args_: '${...time}'}    
    lat: {_target_: builtins.slice, _args_: '${...lat}'}    
    lon: {_target_: builtins.slice, _args_: '${...lon}'}
