
domain:
  lat: {_target_: "builtins.slice", _args_: [32., 44.]}
  lon: {_target_: "builtins.slice", _args_: [-66., -54.]}
  time: {_target_: "builtins.slice", _args_: ["2012-10-22", "2012-12-02"]}

registry: ../sla-data-registry
geoval: "oceanbench._src.geoprocessing.validation"

select:
    _target_: "xarray.Dataset.sel"
    _partial_: True
    indexers: "${domain}"
    
    
# DUACS
DUACS_NADIR:
    name: "duacs"
    experiment: "nadir4"
    variable: "gssh"
    data:
        _target_: "oceanbench._src.data.pipe"
        inp: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/results/DUACS/2020a_SSH_mapping_NATL60_DUACS_en_j1_tpn_g2.nc"
        fns:
            - {_target_: "xarray.open_dataset", decode_times: True, _partial_: True}
            - {_target_: "xarray.Dataset.rename", name_dict: {"gssh": "ssh"}, _partial_: True}
            # VALIDATE COORDINATES
            - {_target_: "oceanbench._src.geoprocessing.validation.validate_latlon", _partial_: True}
            - {_target_: "oceanbench._src.geoprocessing.validation.validate_time", _partial_: True}
            # SELECT REGION
            - "${select}"
            - {_target_: "xarray.Dataset.sortby", variables: "time", _partial_: True}
            
            
# MIOST - nadir4
MIOST_NADIR:
    name: "miost"
    experiment: "nadir4"
    variable: "gssh"
    data:
        _target_: "oceanbench._src.data.pipe"
        inp: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/results/MIOST/2020a_SSH_mapping_NATL60_MIOST_en_j1_tpn_g2.nc"
        fns:
            - {_target_: "xarray.open_dataset", decode_times: True, _partial_: True}
            - {_target_: "xarray.Dataset.rename", name_dict: {"gssh": "ssh"}, _partial_: True}
            # VALIDATE COORDINATES
            - {_target_: "oceanbench._src.geoprocessing.validation.validate_latlon", _partial_: True}
            - {_target_: "oceanbench._src.geoprocessing.validation.validate_time", _partial_: True}
            # SELECT REGION
            - "${select}"
            - {_target_: "xarray.Dataset.sortby", variables: "time", _partial_: True}
            
# BFNQG - nadir4
BFNQG_NADIR:
    name: "bfnqg"
    experiment: "nadir4"
    variable: "gssh"
    data:
        _target_: "oceanbench._src.data.pipe"
        inp: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/results/BFNQG/2020a_SSH_mapping_NATL60_BFN_Steady_State_QG1L_en_j1_tpn_g2.nc"
        fns:
            - {_target_: "xarray.open_dataset", decode_times: True, _partial_: True}
            - {_target_: "xarray.Dataset.rename", name_dict: {"gssh": "ssh"}, _partial_: True}
            # VALIDATE COORDINATES
            - {_target_: "oceanbench._src.geoprocessing.validation.validate_latlon", _partial_: True}
            - {_target_: "oceanbench._src.geoprocessing.validation.validate_time", _partial_: True}
            # SELECT REGION
            - "${select}"
            - {_target_: "xarray.Dataset.sortby", variables: "time", _partial_: True}
            
            
# BFNQG - nadir4
FourDVARNET_NADIR:
    name: "4dvarnet"
    experiment: "nadir4"
    variable: "gssh"
    data:
        _target_: "oceanbench._src.data.pipe"
        inp: "/gpfswork/rech/yrf/commun/data_challenges/dc20a_osse/staging/results/4DVarNet/2020a_SSH_mapping_NATL60_4DVarNet_v2022_nadir_GF_GF.nc"
        fns:
            - {_target_: "xarray.open_dataset", decode_times: True, _partial_: True}
            - {_target_: "xarray.Dataset.rename", name_dict: {"ssh": "ssh"}, _partial_: True}
            # VALIDATE COORDINATES
            - {_target_: "oceanbench._src.geoprocessing.validation.validate_latlon", _partial_: True}
            - {_target_: "oceanbench._src.geoprocessing.validation.validate_time", _partial_: True}
            # SELECT REGION
            - "${select}"
            - {_target_: "xarray.Dataset.sortby", variables: "time", _partial_: True}
