#@package _global_

input_dataarrays: '${task.data}'
patch_size: {time: 10, lat: 201, lon: 201}
strides: {variable: 2, time: 1, lat: 201, lon: 201}

outputs:
    trainval: 
        das: '${...input_dataarrays}'
        spat_time_domain: {time: '${task.splits.trainval}', lat: '${task.domain.lat}', lon: '${task.domain.lon}'}
        patch_size: '${...patch_size}'
        strides: '${...strides}'
    test: 
        das: '${...input_dataarrays}'
        spat_time_domain: {time: '${task.splits.test}', lat: '${task.domain.lat}', lon: '${task.domain.lon}'}
        patch_size: '${...patch_size}'
        strides: '${...strides}'


defaults:
    - /tasks/osse_gf_nadir@_global_
    - /dataset/components/patcher@datasets.test
    - /dataset/components/patcher@datasets.trainval
    - _self_
